name = "ORCA"
uuid = "47be7bcc-f1a6-5447-8b36-7eeeff7534fd"
authors = ["Spencer Lyon <spencerlyon2@gmail.com>"]
version = "0.3.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"

[compat]
PlotlyBase = "≥ 0.3.0"
julia = "≥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
